
services:
  kong-database:
    image: postgres:13
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpass
    ports:
      - "5432:5432"

  kong-migrations:
    image: kong:3.7.1
    container_name: kong-migrations
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
    command: kong migrations bootstrap
    depends_on:
      - kong-database

  kong-gateway:
    image: kong:3.7.1
    container_name: kong-gateway
    volumes:
      - ./kong.yml:/etc/kong/kong.yml
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
      KONG_ADMIN_GUI_URL: http://localhost:8002
    ports:
      - "8000:8000"
      - "8443:8443"
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8002:8002"
      - "127.0.0.1:8444:8444"
    depends_on:
      - kong-database
      - kong-migrations


  employee_service:
    image: doanudpt-employee_service
    build:
      context: ./Employee  
    ports:
      - "8004:8004"
    networks:
      - mynetwork
  leave_service:
    build:
      context: ./Leave  
    ports:
      - "8005:8005"
  reward_service:
    build:
      context: ./Reward  
    ports:
      - "8006:8006"
  website:
    image: doanudpt-website_service
    build:
      context: ./Website  # Thay đổi nếu thư mục khác
    ports:
      - "8009:8009"
    networks:
      - mynetwork
    depends_on:
      - employee_service
      - leave_service
      - reward_service

networks:
  default:
    external:
      name: kong-net
  mynetwork:
    driver: bridge
