# Generated by Django 5.1 on 2024-09-02 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaNV', models.CharField(max_length=50, unique=True)),
                ('MatKhau', models.CharField(default='123', max_length=50)),
                ('HoTen', models.CharField(default='', max_length=200)),
                ('GioiTinh', models.CharField(default='', max_length=10)),
                ('CCCD', models.CharField(default='', max_length=20, unique=True)),
                ('NgaySinh', models.DateField(default=datetime.date(2000, 1, 1))),
                ('MaSoThue', models.CharField(default='', max_length=20, unique=True)),
                ('DiaChi', models.CharField(default='', max_length=100)),
                ('SDT', models.CharField(default='', max_length=20, unique=True)),
                ('Email', models.CharField(default='', max_length=50, unique=True)),
                ('STK', models.CharField(default='', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'NhanVien',
            },
        ),
    ]
